<a href="https://colab.research.google.com/github/Ppangchon/data_viz_2022/blob/main/FinalExamGroupCleme.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/dataviz_2021_data'

Mounted at /content/drive

In [3]:
alldb = pd.read_csv(os.path.join(path,'alldb.csv'))
alldb

,Unnamed: 0,user,RowKey,care,date,ov,phone,site,time,urine,pid,PartitionKey,title,age
0,0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
1,1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,NaN,2022-02-24,NaN,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN,data is not completed,data is not completed
2,2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,data is not completed,data is not completed
3,3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,NaN,2022-02-23,0,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
4,4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,NaN,2022-02-23,NaN,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN,data is not completed,data is not completed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40030,40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,NaN,NaN,"iPhone13,4",01234,NaN,NaN,5,เกษศิรินทร์ ไชยลาภ,data is not completed,data is not completed
40031,40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,NaN,2,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),5,เถลิงเกียรติ เสริฐเลิศ,data is not completed,data is not completed
40032,40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,NaN,1,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed
40033,40033,NaN,bbuogxulur.png,NaN,NaN,NaN,Samsung SM-A115F,01234,NaN,NaN,1,เสรี,data is not completed,data is not completed
40034,40034,NaN,zttpqogiso.png,NaN,NaN,1,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี,data is not completed,data is not completed

## เลือกข้อมูล

In [4]:
alldb_1 = alldb[['user','RowKey','date','phone','site','time','urine','ov','PartitionKey']]
alldb_1

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
0,test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04857,136FD222-FD9F-4E54-AE1F-7282A276B085,2022-02-24,"iPhone10,4",05310,10:50:32,NaN,NaN,NaN
2,NaN,1E6D3D62-4C8A-4F8E-90D1-0DC5BC2752DF.png,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3450101576642,2D331FB0-CBA2-4586-A5B0-CB3CF44DD9FE,2022-02-23,"iPhone13,4",05087,09:59:47,ปกติ (เหลืองใส),0,NaN
4,3450101576642,45197AF7-7CB4-470C-9ABB-37C092BD6B21,2022-02-23,"iPhone13,4",05087,09:44:06,ปกติ (เหลืองใส),NaN,NaN
...,...,...,...,...,...,...,...,...,...
40030,NaN,6B5FA20F-190E-4021-8547-C12308024C6C,NaN,"iPhone13,4",01234,NaN,NaN,NaN,เกษศิรินทร์ ไชยลาภ
40031,NaN,F48C51C0-A345-40D6-93F4-46213267E1B1,NaN,"iPhone10,5",01234,NaN,ปกติ (เหลืองใส),2,เถลิงเกียรติ เสริฐเลิศ
40032,NaN,A986BDAA-6D7C-4017-8E62-A3C104E946B9,NaN,"iPhone13,4",01234,NaN,ปกติ (เหลืองใส),1,เสรี
40033,NaN,bbuogxulur.png,NaN,Samsung SM-A115F,01234,NaN,NaN,NaN,เสรี
40034,NaN,zttpqogiso.png,NaN,Samsung SM-A115F,01234,NaN,ปกติ (เหลืองใส),1,เสรี

## Prepare alldb  Clean Missing

In [5]:
alldb_1.isnull().any()  #ขึ้น True แสดงว่ายังมีค่า Missimg

user            True
RowKey          True
date            True
phone           True
site            True
time            True
urine           True
ov              True
PartitionKey    True
dtype: bool

In [6]:
alldb_2 = alldb_1.dropna() #ลบข้อมูล missing ทิ้ง
alldb_2

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
186,45-161,D2CABB8C-533B-450A-AFA6-B693749CC1C6,2022-02-23,"iPhone11,8",04312,09:45:28,ปกติ (เหลืองใส),0,0-1528
187,45-161,57A5F06C-C840-49EA-9514-A30D3C897CC8,2022-02-23,"iPhone11,8",04312,10:06:45,ปกติ (เหลืองใส),0,0-1544
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
...,...,...,...,...,...,...,...,...,...
40013,ttest,crqcufokmn.png,2022-02-21,Samsung SM-G998B,test,14:23:45,ขุ่น,2,x001
40014,ttest,gzxgflnowr.png,2022-02-21,Samsung SM-G998B,test,14:23:43,ขุ่น,2,x001
40016,xxx,jytlopevha.png,2022-02-17,Samsung SM-N950F,xxx,00:01:06,ปกติ (เหลืองใส),3,xxx
40022,yyy,ivccsksowb.png,2022-02-17,Samsung SM-N950F,yyy,08:41:05,มีเม็ดเลือดแดง,2,yyy
40023,zzz,psudrnccsh.png,2022-02-17,Samsung SM-N950F,zzz,08:41:04,มีตะกอน,2,zzz

In [7]:
alldb_2.isnull().any() #ตรวจสอบค่า mossing อีกครั้งหลัง ลบ missing ทิ้ง

user            False
RowKey          False
date            False
phone           False
site            False
time            False
urine           False
ov              False
PartitionKey    False
dtype: bool

## แก้เงื่อนไข user เป็นตัวเลข 5 หลัก

In [8]:
alldb_2 = alldb_2[(alldb_2['user'].astype(str).str.isdigit()) & (alldb_2['user'].str.len() == 5)]   # กำหนดให้ข้อมูล user ที่เป็นตัวเลข & มีตัวเลข เท่ากับ 5 หลัก (ตัวเลขเท่านั้น)
print(alldb_2.shape)    # ตรวจสอบขนาดของข้อมูล                                                                        
alldb_2 # print data ดูว่ามันหน้าตาเป็นยังไง

(37974, 9)

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999

## แก้เงื่อนไข RowKey เป็น String

In [14]:
set(alldb_2['RowKey'])

{'BF5BE066-9ABB-441E-8E7F-3A79C3DC4018',
 'C5DE322B-4CE9-4D35-9BA2-8CCE20C8ED9E',
 '5658EEE5-229E-4896-87C8-E3D5FECD072B',
 'DF3E852C-66CD-400A-B38C-E4186D2B1DCA',
 'A9175878-6B88-437F-86B9-32BEDFBCB96D',
 '8C5851A1-82C0-483D-805B-92BF27D8527B',
 '063DCB7F-0634-4543-B5AA-31BB63C71F6F',
 '1A1DDF63-F7D5-4599-ACA3-03740C999BE7',
 '5DC63778-8A5E-4468-A713-4E7EDD0085C1',
 'kkezsxjcbb.png',
 '697A9429-34E2-402B-8C74-2EE100AF109E',
 'afxxcvdqxq.png',
 'D9FA8686-D6BF-429B-A5B5-ED1FB396653B',
 'nmjgdvrpvf.png',
 '06BB7895-C513-462E-8C01-766CF77DC6F8',
 'twuffbxale.png',
 'airzpkuynm.png',
 'xecnnvosuh.png',
 'D6FDC901-9873-4FE9-B4EE-3EF2307D4377',
 'whaivilhij.png',
 'pjjoyuxxrz.png',
 'etrblyiyle.png',
 '30E2F5FB-F616-4EA4-B484-12459D80DCFA',
 '57F52B41-C9BA-4064-8A83-C45AA82F9C82',
 '21D0D33F-8C32-494E-95AD-3F8C6A2F3224',
 'A4D24A5D-6D94-4B62-9C8E-53257714FDEB',
 '77C69B0A-7BA2-4766-8ACA-E1C57EFB3271',
 'yecwvmzsws.png',
 'fcaktrkedv.png',
 '313ACAD7-718F-4AC5-944B-3CE6F627273C',
 '2AEE0B68-B1B8-4D3D-A04C-A97202E29759',
 '8B9DFE8D-AD36-4EDA-8105-91C3ED32DD3D',
 'F1453AEE-DBFB-48F5-B442-B7237E292206',
 'exrvwptkkd.png',
 '46C4294A-130A-4E8C-BAF2-B0028E590331',
 'sbcilpyrpt.png',
 'igzvnhhsak.png',
 'fvveeewkak.png',
 'E37C97DF-86B6-4F64-9697-1078912253DC',
 '5E40205F-4339-441F-BA9C-1455F9DD758F',
 'wexacrzbxk.png',
 '6F56B424-C1E1-4420-939E-5BEB732C20D7',
 'yvxcyttlmo.png',
 'F3430914-EA8B-4F21-8D60-B54C0A2296A3',
 '895FA1E7-E1F6-421C-8B97-8756F48AF84A',
 'lcasyjdocf.png',
 'bxdfranwtz.png',
 '2CAB1DDE-502D-48FC-97B9-C0514DFE0654',
 'B8FF14F5-8D60-4352-9D23-0E33F9F1A3C3',
 'A4C5F263-82C0-40DD-AB91-0A1E32AACDDB',
 'fqlgygavvr.png',
 'ukwyajxwqo.png',
 '199492F4-8404-409C-AF25-132045DF8512',
 'E8C8D668-85CB-423B-9305-597332090513',
 '3C5A1D59-5244-4BA7-A55D-B5490950DB28',
 'E3018509-3B2C-493A-9522-997D339D6690',
 'pkmpcxfxnj.png',
 '4A3F94B3-79B8-41D3-9EBF-483F3D418111',
 'B3EBDA3E-1242-4BDA-A116-E2A2F7238767',
 'BE424066-FF06-4D3D-87A8-9D2CA2B7D8BC',
 'fanaxhahei.png',
 'fxcsyddtax.png',
 'zsoyfzunzp.png',
 '74F4DC46-F913-4DAE-B0FD-92087B681D51',
 'E20023E4-6069-4DD7-98E6-C03C609A570E',
 'D5D7CCED-E1B0-4446-9EF8-1E3F83405381',
 'cocmbcxvey.png',
 'ADA30107-A37C-481F-BFF6-6E23341311EE',
 'mupfrsizdu.png',
 '599100D9-EE20-46BF-BF12-0B675167CE21',
 '0EE01E21-E600-4EE9-BCD9-3522A18C4A7A',
 'fcmdqypqmt.png',
 '93199277-7197-4B87-97FE-259295C78876',
 'chtffzbevs.png',
 '3777B6CF-7FBA-4402-BFF7-11EC335EB688',
 'FAB94302-7BD1-4223-8587-827E43452619',
 'wvjuleyhqe.png',
 'D275BD6D-7F0D-48FB-98A5-AEFD50C600BD',
 '8EA35B57-E8FD-4820-81E9-B71CA69EAACE',
 'gukaqsjxkf.png',
 'gglidedofd.png',
 'nxbeiplwmy.png',
 'A15D4744-EB01-4795-8727-22BBECA7A31A',
 'dzsdsyadbl.png',
 '3C728487-5AEC-4951-A6D4-4865EB3FBC29',
 'whhvinjpit.png',
 '4FF42DAE-F173-47A9-B276-62CD954AEBB6',
 'nlkissboxn.png',
 'D68A1FEC-AD6A-44B8-8A1A-26C839A37521',
 'FC30E6F8-C017-4E43-8898-208BC50F9811',
 '2C64F583-EA00-4AD5-A947-89C357FB1C31',
 '217C397C-C733-4EED-941C-690E41C333E7',
 'larqndqnlm.png',
 'B851493D-474A-4FCC-BCC3-7E5783121544',
 'caznxlwrsj.png',
 'A85FB3DD-97AD-47BF-A62C-A095A8C415A8',
 'uktfevjrto.png',
 '38C6E463-492E-4D2C-870C-998186F9ADCA',
 'fxhfwbpdrl.png',
 '1D2EAC82-EC44-4E54-8CC6-C53C39AFEE47',
 'aqyuuzpuhm.png',
 '31369FB9-06C2-48BD-B4C7-B26DC6BAB375',
 '14FE79D9-2D65-4508-80ED-1642FD21795B',
 '3A032604-4621-4C95-A53E-72476A612B7A',
 '17A12D32-26CB-403F-A1E0-3ED035499D45',
 'BE6D0F9D-0A4D-4D75-934A-777E890E355F',
 'cmclbgzmls.png',
 '160FE9EB-0635-4BAF-8AA6-52C296AB0073',
 'FBAA40B4-042D-4BF3-86EE-B914D9E7E006',
 'ulqksoonqy.png',
 'FFC31A4E-40C5-4F01-90B0-9990E556AE96',
 '2A5B48BE-FAE5-4A05-A710-2A906565B08B',
 'psqyflplgy.png',
 'vaqwdfldoh.png',
 'msxlmvdlbc.png',
 '807A638F-D62E-46B7-8843-AC3708E9E14E',
 '3732B162-F4B3-4D2E-AC47-FFC1D396C3B7',
 'C278479F-5C14-4B76-9D6A-3956A22E6F53',
 '79D351AE-7556-4DF5-AAA3-C739A16EEC51',
 'feoxmcwhah.png',
 'gysfohggkv.png',
 '6CB7DE66-7DC2-4967-9D05-D48CEBDAF30C',
 'iepkevrgww.png',
 'D5C69A8D-9305-4168-B865-5D9F28990792',
 'A028302B-85AB-4A95-B8AE-110B19FABCDC',
 '1F72C172-360B-4141-B3E4-628B965FAB5A',
 'ufybvuxopc.png',
 '3ECC8931-59AE-4C76-9106-A4A4BD2BD18E',
 '88507494-FF27-42C6-9FB5-A9531E427280',
 'wrvsjtmtti.png',
 '89176992-535B-41E2-A7AB-4CD3EB819620',
 'A66B3229-C91F-4FA2-809A-01B031BF55BB',
 'D2BBBD33-D610-45D7-B98D-2325F8FC46F5',
 '6F95D193-3E3D-452D-99BD-705D0271030F',
 'bdsvrpfcvb.png',
 'mlycdotpne.png',
 'FFDD490E-55E5-4E26-99EA-CE688D21BB81',
 'fghnobybmj.png',
 'dpkceynpxe.png',
 '83DADC36-54EC-4696-A86E-CE27F85CFDCB',
 '53FED7B5-C847-4306-AB49-B19E9DA1C9B1',
 'sixoudhith.png',
 '29F8B203-E04D-4AFF-9793-62E16CA9AF22',
 'didsyqrbop.png',
 'fpenlbvihj.png',
 '6F83069A-FCD0-4619-8384-F92D17C2C0AB',
 '7925DAC3-3ABE-48B4-A726-176F32A50D2B',
 'brdgaefjjg.png',
 'F81645AD-8889-4C6F-A760-F7A778E5EFF3',
 'dcypibscjn.png',
 'pajnvzbtaj.png',
 'djtbislwwi.png',
 'mcictguagp.png',
 'C6FB66C7-FDD5-489F-AAE5-5116C48D7FAA',
 'otjqsghgeb.png',
 'pfgokrhnem.png',
 '329B8DA2-60E3-4F3D-B3C3-BEFE65B1703D',
 'ykwhkafpcf.png',
 'cyxycezeqr.png',
 '82304D36-FB31-4CAA-BDF9-3BD6667A1C3C',
 '33556D99-E6F1-411D-9022-6C7D1719BE04',
 'ejobqoldgs.png',
 'CACE7C12-1994-4B33-B587-33E7CC1EE880',
 'sxhpykwhju.png',
 'D76622D0-41ED-4BA6-ADAF-A8D8F4EC5FBC',
 'CE6F0D64-C261-41EE-9234-F2465A13A854',
 '64139FCE-E784-4472-96EF-96E6F2D03D9E',
 'qdomxijxcq.png',
 'klbnebkzif.png',
 'tpbmdikvlf.png',
 'qxgaxxqstq.png',
 '1C16F528-481D-4736-BC4F-C6815F1FA953',
 '35110D08-D39D-42F8-906B-FEC009981F82',
 'oxjzuvstid.png',
 '011E2E06-77C1-4D67-BB42-3B5CF209FE06',
 'wfkknfdgnv.png',
 '0935B515-CC66-43E4-BC71-F4F117B3A5C8',
 'E589412B-C862-4583-B57D-AAB395928441',
 'EE461AAB-1408-498F-BE87-D9554727FB20',
 '91FB2D0E-1037-4A34-B959-E9602F0CAF8B',
 'awjamrfqut.png',
 'F394D3C1-4732-462A-8918-808256B88498',
 'zbwgaugxwb.png',
 'ayhrhwigfb.png',
 'hdzoruoxzq.png',
 'D840EFDA-D00B-44E8-B455-DC446051356D',
 'ydykqydugx.png',
 '849828CF-F0A7-4CF3-9D74-C9EE79735DAC',
 'DEB45E01-BE51-4ACA-8DFF-F1F68AB5C87E',
 'kogelebtxv.png',
 'nacgqiwgkp.png',
 '307ECF1C-1018-4EED-A29C-BC7D2A9D09BD',
 'vratfochgt.png',
 'hphqpxqnrt.png',
 'ehaowmmmon.png',
 '9113B196-E23A-4511-AAE4-906C29402023',
 '1E0751FD-4635-4B67-A72B-FBD1B547FED3',
 'tkaaenesju.png',
 'pqqawghjrr.png',
 'rrfkbktkqc.png',
 '73D47C0E-7685-4515-AFD4-668FEABB4EF6',
 '13D3D345-0FD0-4746-A7C3-478BE8EA8C12',
 'vplmijarix.png',
 'fpxhfpzqbx.png',
 '945921EB-9ECC-4762-9B70-E181F18C2D2D',
 '73E09379-46E8-4FDB-B0C7-67EF1C9C9F9D',
 'pxkmyqmtrk.png',
 'sxlvthpgkc.png',
 'qjywiuzkpj.png',
 '867EE44C-1872-44D9-9E73-4A585C09AA32',
 'C57D0CFD-0B6F-4A22-BE1C-6D890328D894',
 '09C1FAB1-1220-400F-8DC7-31602CABBCD1',
 'lsrwwufifx.png',
 '302033E5-E44B-4CB7-B955-35D985967372',
 'fbhmsawwja.png',
 'sbdtmvqzru.png',
 'eurnbohplt.png',
 '3B19E778-5F38-4704-8406-988859FC0065',
 '4F56DBDD-DB9E-441E-8B92-7E0BB538D5F3',
 'AF20DB61-E451-4E16-98D0-DC1490CF6F08',
 'zmcypnhucy.png',
 '6FA33D60-B58B-411C-AAB6-8780A2566572',
 'psdrxdjcqi.png',
 'uhjrvtfthu.png',
 '2CA81D8E-8FC4-469D-B5F4-4DD430DD491F',
 'btjlqawxoe.png',
 '9B58C9D3-3D1A-494C-A18E-83075B428BB1',
 'aoquvmpngo.png',
 'qzubqerorc.png',
 'zczbvooylv.png',
 'vwdwruytbo.png',
 'E3726746-CC9A-4E49-8AC7-A65DE6AFAB5B',
 '90522350-81BA-4089-96C6-9058741E1E4D',
 'oohyzktqpe.png',
 'wouffngfxh.png',
 'FB9EBA09-5C33-465D-9367-EA6CF70F4B1B',
 '764F1FF2-5F96-4976-8BD5-1158E59B6B5C',
 'B5448B1E-CDCB-4D7C-B776-53940C17443D',
 '2144FE00-2293-47B2-A390-3CF3249C65F1',
 'E6566A5D-6F51-400A-89AA-838E261D66C9',
 'E3B3328B-9754-4040-BAD8-12C7F20296D7',
 '07B713A1-5A49-4B03-AB86-BE0BEBB51878',
 'rcshxysjvc.png',
 '391D2A4F-416C-4A81-A968-7D98D998976D',
 'E6EAEDB4-36B1-47AB-885F-069DF3D40650',
 '345B0469-032A-4139-AC10-1D416937F5E8',
 'llqwqnvxbb.png',
 'F4629E73-1052-4F97-8107-E66874254605',
 'oxeeevnesw.png',
 'ofbhriezko.png',
 'zkhteorhus.png',
 'D4FA5FB6-9FAC-4D86-9279-30CF9E71698B',
 'B38EABB6-DB1E-4FC7-827A-20DAF8F94548',
 'DA258F00-39DF-403C-81A1-CCD0DCF64A45',
 'oggqdhvyyg.png',
 'B48DB3C0-4675-4DDC-A5AF-04E0F42B5578',
 'C6B703FF-AAF1-4439-B9AA-BD6C0FE14419',
 'rhqraazbnd.png',
 'lfxksinkgm.png',
 '8AEAEDBE-5AF7-4077-922B-AA553703F007',
 '6F287AE8-3E8D-420C-834A-5FF4CF6EA8DE',
 'oirqwpmlnh.png',
 'zubyolayik.png',
 '5EEBE30E-3D50-4C0D-BD23-4E3C3F6288AB',
 '22235FD1-31C3-4F3C-8256-AED9D36929E8',
 '0C9146CE-6855-4F87-A4C9-3A492C39A7F6',
 'uquteufazj.png',
 'bbxogrkbnl.png',
 'C4DCC571-DF6B-4191-B41D-EF20F8B73784',
 'tgayqefnor.png',
 'itnnfoecnz.png',
 'uouvwgtnnj.png',
 'akfisyizvo.png',
 'DAC97296-EAD4-4A4C-8E2C-542C6B616EF7',
 'bvqpoibfxp.png',
 'DB962499-149F-4ED6-8C46-C6FF44251ACD',
 'mfxiporynx.png',
 '98E81ACD-FAB1-4857-B969-93CA8052AB32',
 '5FB8812E-F994-407B-B647-75C34CF182AF',
 'kiuqvjnzth.png',
 'B51FC3A0-9103-4652-B109-16DA0F6F67C5',
 '9B70C2CF-0B7F-4131-976F-B584219C44D1',
 'A4023987-89F9-40AD-B8CB-4EBBE29838E3',
 'D6782069-623A-4787-A58C-E19BD233AFD1',
 '995BB9EF-131F-4259-8D9D-1948842390A7',
 'pacoohazxx.png',
 'kqbicqwgeq.png',
 '5BED2B08-3B62-4021-A6AB-997452923C3C',
 'uqfwpqzvpv.png',
 '290789E3-EEBB-43F5-9014-77B8457C5274',
 'ntiopgeecc.png',
 'llclysqlug.png',
 'ypwjqlscpj.png',
 '9318469F-F988-4237-87EF-35DA2E498016',
 'cntwidzyjx.png',
 'wyedzdtgsa.png',
 'ztbdzqnlgr.png',
 '48EAF643-9764-4B9F-AECF-915A3F27E7B8',
 '5DE4E0BC-4C37-4280-87C7-606688978A85',
 'C1E44D49-5F69-4C00-A6D0-76A00E99D08E',
 'FB8B7217-9894-41A7-9A0A-89A9E57CBCCA',
 '62350CA4-D0CE-454A-A1BA-8B469BEC3818',
 'F25A50F8-5C56-4A6C-8BAD-285D41FFD477',
 'C29BE670-E6DA-4C47-9461-5EA2AA129629',
 'nyzybegodd.png',
 '0739EC50-5E53-4002-B5AC-2044BC246D7A',
 'FE9D6DBF-89F7-4638-9BBC-F0CC56E3F187',
 '5157B722-D372-44D4-A5A1-E4F82ED22BA2',
 'qogochqspd.png',
 '04C07971-F4A0-4214-9C66-EF9D8A915212',
 'cfibmyhpci.png',
 '1F53B7F1-589A-440E-95AB-0FAE70B2C150',
 '9B336A78-214D-42FD-88E3-596077E9B33D',
 '1A995963-E975-4E3A-9DFE-DF0B5F10C7E2',
 'erarqivjuf.png',
 'wokbattcfh.png',
 'ccidxkbpvg.png',
 '2DE16310-2E2B-4C4C-A661-3D1AC49CF82F',
 '487172A3-007D-40E2-900B-8567146DC8D3',
 'celdmzscjy.png',
 '3C79FE7D-7AC1-47B9-8890-664C71672796',
 '7C2D6F38-939F-4212-BC01-71365643F1DD',
 'BD88D383-2456-4547-8B7C-55A842C9C10D',
 'ikngktgjko.png',
 'lsxwasvwcj.png',
 '59434D9D-19C4-49B7-BEB0-59760588CC43',
 'jtinrthhht.png',
 '0F410BDA-76C4-4655-BF4F-8C0683111395',
 'fjibjdkfro.png',
 '9BA310A7-D06E-46B4-8B6C-C17FF734DBEC',
 'gnzeexqgit.png',
 'C8EEDE20-0299-4BF1-B944-05791458D79E',
 '423BA477-28DD-4827-97C6-31FF7A6EA787',
 '4FBCF32E-AB76-4CC7-A091-2BA439C111BC',
 '8CF81236-8202-4DCB-AE9D-0E7E088A3EC5',
 'nnkxbhvfss.png',
 'A6AB9EA3-6F47-4181-B01E-C9AD15502B8D',
 'qnxaddkdtu.png',
 'epgxrvuycq.png',
 '78B741AD-1159-432D-AC54-DA77F25C7775',
 '11C1E87E-EC94-4D44-81C3-57FAF64B7DCE',
 'inkyijzkst.png',
 'gxpnaqowso.png',
 '211C9305-D625-4EF2-9BF9-D1A796F6E6D5',
 'F3B25646-3EE2-424A-B5AA-86CF9D99EEEF',
 '479B6524-225D-467C-AAAA-A16BB171435A',
 'grtuvpbdad.png',
 '25A06F02-6F64-4009-9DCC-F09C6F3EC6DC',
 '6C7B12AC-F986-4B2B-899B-5136ED879B40',
 'wzngjqhkgg.png',
 'wurqczfmpw.png',
 'pyhffegojh.png',
 '74807F27-49F2-43B0-BFED-8D25FBB8CBEE',
 'E8CE2ECD-7E18-4993-A9E6-F634F61F4CC9',
 'rjfxhhbhsl.png',
 'B158F5E6-83F2-42B1-9E13-94197F51428A',
 'pwiwotafkj.png',
 '56618E0B-A132-4345-B64E-D04A5C7057CC',
 '7AE547F7-1C16-44A6-978A-9025EDA56EEF',
 'vuvhdtvoaz.png',
 '6CCCAD3F-5117-44A7-8EEC-1DA596DDEE0D',
 'vyorlsfopt.png',
 'tbzfovdsjl.png',
 'CC700F6A-16B4-4F53-95AB-FAFA404A034D',
 'gyzyiuxtqs.png',
 'mhtnurtqjg.png',
 'FA0174F6-11AA-4A3F-A7B5-DF2079314D7E',
 'DB61882A-F212-40D2-868E-CCF4E5A61A2A',
 '232CB854-D1D0-421C-A86D-D34AB1395756',
 'D7E01AA5-3FA1-4AC6-9495-EECB5865749B',
 'wqdccnbugq.png',
 '77B04F8E-7768-4D56-908D-B269D7A7171F',
 'dybcvwzbix.png',
 'EE067D69-1A7D-4C4E-8D56-D9966919D56F',
 'rxrcteoqwv.png',
 'xpbfsswovc.png',
 '6368C3AA-30A9-4E47-86D1-E67126A5F1D0',
 'jnxyorsbxo.png',
 'yanwwyrixc.png',
 'mxavcozupi.png',
 'msdnhsjxii.png',
 'EBB5F7A3-FCC2-4F05-8882-3D53DA34D475',
 '58993F75-6236-4C4C-9937-3BCD476329F1',
 '82DE6DFF-A385-44E3-9AC4-C96C003F05DB',
 '9143756C-186C-4D70-8B52-1B2CB73413A0',
 '71C71A21-9B51-4F0C-B30C-D04F47F61645',
 '8D59F9BE-7C1E-4E03-9B6A-B8225FEFA83D',
 'ckborwuyeg.png',
 '6089A350-8B83-47A1-B2F2-1054D166B095',
 'enqtcpjbpv.png',
 'kbutzofbdj.png',
 'bjscavuapr.png',
 'dxixwbplrl.png',
 'tikiurtinh.png',
 'zehoptyaku.png',
 '2ECFC760-9BCC-450F-91CC-B3E07E99C8E0',
 'D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663',
 '067008FF-3E19-44C0-A068-B75FD5902D33',
 'CC8299D8-6190-4937-9956-B4C73B1545C8',
 '25B62382-4475-463B-8303-760DC7F005C1',
 'D76A9A0E-80C7-4121-9C69-4BC9CB196037',
 'kgwbwkhdet.png',
 '23B9D756-5CDC-4FAB-9806-AAB20C8A1479',
 '533F2476-2BC2-4D8E-A2DB-0B9EA687D086',
 'oywhaenfup.png',
 'mhrcybtohy.png',
 'C8EB74BB-17CA-4EB1-8252-E49869EE1089',
 'F7047534-90B4-4864-960E-397087FA9631',
 'opjljouolj.png',
 'nyocnpofnb.png',
 'zuwznygtcb.png',
 'A1BDF195-806E-458D-AD89-7328E43A96DB',
 'zzxlseotxx.png',
 'ipdjvawpco.png',
 '80EB85AE-2FD4-4098-8E5A-53483051C472',
 'ojnwgcqtde.png',
 'ynvuzxffxn.png',
 'AF770896-1778-4CE3-B863-99B0D8FED564',
 '963A9FF6-7B7A-4A15-A256-7905F7A9D25D',
 'soqmtlonls.png',
 'cxmxjpwqyq.png',
 '5E45891F-51EB-46AA-95A0-E21CDBE2FE02',
 '47EC5513-9A01-426B-8153-49B3D6C335A6',
 'C46FA98B-38EF-4135-B6A0-0EAA65963C18',
 '3F25D61F-4BD4-498E-B8A7-31D673777038',
 'gegnsisaoq.png',
 'voxzxvmtzh.png',
 'ucjbnvujcl.png',
 'ysnqfuhcno.png',
 'D6D5BC1A-156E-4FE9-92FD-40365E344588',
 '0595CF77-6371-4FB3-879C-36D64BEC9415',
 'cxxudzdhye.png',
 '8F9806EF-B463-468B-9991-A17C67BE64C2',
 '38E97BBA-8FEC-4641-9A10-CFA6622C3F96',
 'umqivjgbzi.png',
 'zpisvhgwun.png',
 'ieafbkxnww.png',
 'pgbyinjcby.png',
 '729C7B38-8B37-4A49-A8F6-6CB0298B5BD5',
 'xwvrhoocqm.png',
 'A3EB0144-BBAF-49D4-82BB-B5D62D286E74',
 '48027B80-078F-4FF3-8164-74820704B13B',
 '118CCAB5-40AC-4C70-AD89-7B245EB28E81',
 '81B87F03-8119-4B0F-85E1-8B817C2CC206',
 '516A40D3-3AC7-4B85-85D3-891B19280F97',
 '1407A8C9-4CF3-45DC-BBFA-3B20A987ACA5',
 'D3D31C05-1B66-4130-8175-7D6A48CD9921',
 'gmvhsyaocq.png',
 'ugvaajgdzm.png',
 'zczpavkgge.png',
 'C44BB58A-45F3-4EF1-AA7D-9E11C6624496',
 'htbembyygp.png',
 '05D5153B-5431-4E37-84FF-B05B461718A4',
 '09FA1A58-6FDD-4052-9FA8-9F4EFD06E212',
 '3E6FE0EB-F124-4C3E-8FA4-32BA0CDF723F',
 'oewtobvkfq.png',
 'C221F81D-17B5-4654-9E1B-80324ADAF14D',
 '15F0B041-B370-446D-90B1-01E6C142D10E',
 '55EE43D2-D033-45B8-A1AD-1F668A7529EE',
 '658BCA6D-6BD7-476E-A0CA-A0C4F52DD4C4',
 'qhifrxmfgh.png',
 'ED2DA4F6-6232-4B53-883D-51115D6B8C6B',
 'milvsydxtx.png',
 'A5F6DDBA-7AF4-492E-80D5-42543D86289D',
 'F9F86058-A6F0-403D-9FC1-9EC810FBBEF2',
 'zqpbwapgss.png',
 '7E7FCEDA-ADCD-493B-83A5-5206412E752D',
 'E80450C5-6F21-487C-A885-E1EF0C945187',
 'dhohwuydqh.png',
 'nifksbsoex.png',
 'bmpajsjnio.png',
 'A4F8676E-48B1-4C50-83C1-E4BCA9D16B01',
 'wcxneflbcf.png',
 'vucrrxzhxe.png',
 '7C7254A4-A34C-44F7-99E7-F5929647F609',
 'pwobqxucgj.png',
 'nwmtnhmuqm.png',
 'cubpcloouj.png',
 'gxoqejgeaz.png',
 'ybrsusadtk.png',
 'ndnmkfxhom.png',
 '4C0A67EA-7646-4704-BBFE-A75AB4510265',
 'fjnlygcowt.png',
 'CDE29BD9-C018-4A44-BE50-98B48CBFC5D4',
 'D8458B39-A9AA-4829-A40C-9441638FC94B',
 'olbjbxwoxt.png',
 'oagamugykm.png',
 '857075EC-02C1-454F-A32B-EEB547794826',
 'itxrmcaqpu.png',
 'vkmhajvxho.png',
 '3713F973-3AF5-4D90-866E-99A66CE9BFAC',
 '489E75F4-E5AD-4472-B47F-560A7855817D',
 'yjlrccslhq.png',
 'lgdtaielwj.png',
 'D6300C73-7251-4BDF-ABBD-8D4896B61F27',
 'jlxkhvcjhr.png',
 'pylbsibiem.png',
 '6849901E-B38C-43F3-9640-89164896E64D',
 'CCD3953E-A00C-4E7A-A209-9361792F6C05',
 '02E6E984-352C-46BC-B590-85589509FDC8',
 'kjrcztpwod.png',
 '57502753-F763-4CE2-8983-9EB22D79DF78',
 '86AA9C2F-B441-47C2-8545-482024F40B30',
 '6C56DC23-D529-44FE-833D-7E905DE39A45',
 '0CF44568-151D-41B7-B902-13124C289538',
 'C331ACF5-7E92-477A-B627-7CE354473F78',
 'D90CDD64-6E4A-49CA-AE7C-74BE91235602',
 'FE04E188-B0A8-4C61-8A1A-6D7D6B54765D',
 'A4D07C62-12F4-4B71-BB62-59A9EA8B477A',
 '43096F73-64BC-48AF-9F52-7C5C95937262',
 'D325B214-78B3-44FE-B8A5-40E13718380F',
 'kpbyyenijt.png',
 'E1DCDF6C-8D22-4928-9E46-C4441B3ADAA6',
 'wqwbhqluue.png',
 'oigfrxcgfp.png',
 'jetcmjyroh.png',
 '78FA3E29-180A-4114-82E1-B510163F5F5D',
 'AB3FDCD8-388F-40B8-BD92-58052A394D0D',
 '9E9A7D95-1079-4A2B-B6C2-C3339FA93811',
 'kyyspilgtw.png',
 'F25D017A-90BF-4AAE-A8EE-7D73BB14D64C',
 '83BE6584-CEE1-479A-A0F9-7D696EA72E06',
 'ffqbtrqpjh.png',
 'A9BC0327-00C7-42BA-87F8-8D97777BC6C5',
 'jjpomdqvlh.png',
 'qwhuuqijco.png',
 'A3D37E81-4E15-4398-B11E-DD140C9767DD',
 'wqwbrvpqhb.png',
 'ivpjqwwxmc.png',
 'skojdumkhz.png',
 '89405C26-2D50-46E4-8831-207DE6059392',
 'B767E4EC-E7C4-46E7-9CC2-8F02DCE512D0',
 'ioxdsokbzl.png',
 '3789AF64-24C4-4D3A-BFD6-7A1F1BA913D1',
 'yhescvtrxv.png',
 '5D1090BE-BC11-4849-B010-B5A9B0E897AC',
 'wcvygrlcbr.png',
 'B1C0C61B-8442-4559-9F93-E32C4E5F1C16',
 '03E2D7DC-FBA4-44AC-9889-4D343A81E8FB',
 '5DF8A1E1-E753-4D7C-8459-968FBB08EF15',
 'FDEE6AD1-9A14-4667-A62D-BE7C3DAFCC75',
 'B8BC9787-8194-43EA-81BD-4AB1C4F11D43',
 'A4CD94BD-C1E7-40D4-A2BD-C9C6AFCCFB9E',
 '71ABB844-7DD9-4F22-BAEE-A1B44823E3C1',
 '78339941-BE52-4D86-81C6-E9B331F03530',
 'hntbjyqtvh.png',
 'qywttxgmbr.png',
 'AE225C30-57B7-4F23-B9F4-8D1366E3B88B',
 'glfllbootw.png',
 '15E436D4-0830-489B-972A-31A8D8FE3E3C',
 'yeiubksfzi.png',
 'xgxbkmbsqi.png',
 'qcifazrnfe.png',
 'wewwvhdybf.png',
 'bwotymsacs.png',
 'A1B50A6B-4E84-46DE-B861-2ECA28E9B57B',
 '3D6E50DB-8CEE-4A13-AD7C-CEADB97F9CB0',
 '4B0A9C79-DAA2-4F72-8DDD-280288E6145D',
 'fbycnqrqze.png',
 'pxizvkeymr.png',
 'rjbiofethd.png',
 'kaxgdawhrt.png',
 'wcbbpqwplg.png',
 '70FDFCB4-74CF-462B-A805-7AE7A13451D5',
 '10EAD621-38CF-4E4A-8552-B344AD98F65E',
 '9D8F73D7-2F79-45C3-A03D-77C248D4A1C1',
 'EB3C53DA-8715-4F5C-83BB-26426C8AD223',
 '2EA0339B-CF56-45DD-BAAB-96ECD96F22CB',
 '675A64D7-B51D-47F3-9C51-1B6B335B996B',
 'kngrksmied.png',
 'FF76C302-D8DD-496A-80ED-28BE698318B6',
 'efutephgmi.png',
 'kukhagiqsz.png',
 '37AD833C-A3C0-432E-B38C-161AAD1B530F',
 '47745212-2C0F-4479-AB60-89A55483118D',
 'yegfpebulm.png',
 'FB0BFF60-E870-45DB-9CE8-55B1BD823023',
 'AC14F8BB-7873-44B1-A6B7-782AB735FF25',
 'afdnowviuu.png',
 'jzektzhpmc.png',
 'zkwpidlddm.png',
 'gbylxemthx.png',
 'qjmwitenuz.png',
 'BC4F0C82-F5EC-4E4A-AD04-04E8DC8012A1',
 'mysvflsvts.png',
 '473432AA-5873-4A63-979C-47998CD9897F',
 'ytvavsokdx.png',
 '1EDCD8A3-16AB-4FB6-8AB4-CBA11CC0CFFD',
 'ykdtmzhnqs.png',
 '63799674-EA14-40CB-981A-5F70C04B6FDF',
 'jesynttafb.png',
 'eoofbrtiyv.png',
 'ieertdmvts.png',
 '6BA56ACC-5384-4B62-9282-F4157049ED29',
 'hdhsqtskax.png',
 'iuukitfrym.png',
 '2A5B17E9-DA02-4FA7-9FB0-D9765357DB2F',
 'rdrwcqfcgi.png',
 '4260CC79-8423-41CB-943E-1275DEBAB561',
 'dzobnrdugn.png',
 '633DE77B-243F-4249-B547-F05A2B1ED15E',
 '1F59BE40-74B1-4D91-A831-F68DE3043AAC',
 'btuqfatums.png',
 'howxmbhcjb.png',
 'B944B6CF-7576-49F3-8B8F-99DCE8E35B48',
 '01118877-4EFB-4183-B6D6-5B9CA812100B',
 'pgjvlvegzj.png',
 '67179B29-CA37-4A07-BA87-1FFF4F150446',
 '2F5D0022-4347-4945-A5C6-F088F7D872EA',
 'gdzjfgzsut.png',
 '127025F6-5107-46CB-9A1D-10DBE59E2340',
 'vtqwftfppw.png',
 '6E62377D-A528-4183-92D6-22F261D6A919',
 'dqolryuzmj.png',
 'hxjjknygti.png',
 'txylbfayxy.png',
 '132E768A-D5DB-405E-A6D5-1EE2B29AF45B',
 '6C7078F3-27DF-43FC-9F8E-CB0BBBC598D7',
 '074A4966-DE4F-44E5-8218-C86777184A9F',
 'ECA02F41-3A42-430A-820B-B3D6DC7E72DE',
 'bvaetarxfz.png',
 '5674B267-E62A-49A0-A1BC-4945B8A90090',
 'aghxgmxrsp.png',
 'fbhjyfchwz.png',
 '58BDB9D5-B8BB-48D5-BAFC-529CE343CC3E',
 'lqdxyybsmf.png',
 'lhgeajxxlt.png',
 'E20E96D9-3E27-4FED-A578-B46B1AAA8A0D',
 'B90FA6BA-3C6F-4E85-A4E4-1E751226702D',
 '31B7C9CF-96F0-46D6-942A-DA2C7920BA86',
 'xtntlrljbu.png',
 'uihimoxdvq.png',
 'prjknadxzp.png',
 'ymypyigbas.png',
 '8DE1A824-881F-4FAA-B538-52F9F0E0C247',
 '81EBB70E-FA81-4DC4-9CAA-6B2177E705C2',
 'gkzezqrzqx.png',
 'E6074120-02F5-403E-8D93-ACF0C5B0DF3E',
 '1F774C62-1B92-49CD-9D55-CAF03BF02639',
 'qorgjlxntt.png',
 'cpqvzgfepr.png',
 '447336D6-4EA4-4649-9EE4-C62F0104AAFF',
 'hllrrprjcu.png',
 '5BD683D2-42EA-44B1-B34E-D66A5E5FA435',
 'yvnincnsjd.png',
 '3C5DB2DC-FADF-4A38-BAF2-600B26084D0F',
 'F8143532-58A4-4914-AC73-A4DD4DAB85C1',

In [15]:
alldb_2['RowKey'] = alldb_2['RowKey'].astype('string')
alldb_2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13-08-39,มีตะกอน,0,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14-22-22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11-36-34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18-10-29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),1,99999

In [16]:
print(alldb_2.dtypes)

user                    object
RowKey                  string
date            datetime64[ns]
phone                   object
site                    object
time                    object
urine                   object
ov                      object
PartitionKey            object
dtype: object

##แก้เงื่อนไข เปลี่ยน date เป็น YYYY-MM-DD

In [9]:
import datetime # ทำการ import package datetime 
alldb_2 = pd.DataFrame(alldb_2) 
alldb_2['date'] = pd.to_datetime(alldb_2['date']) # format = "%d/%m/%Y" 
print(alldb_2.shape)
alldb_2

(37974, 9)

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999

##แก้เงื่อนไข เปลี่ยน phone เป็น String

In [10]:
alldb_2['phone'] = alldb_2['phone'].astype('str')
print(alldb_2.shape)
alldb_2

(37974, 9)

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999

### แก้เงื่อนไข เปลี่ยน site เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)

In [11]:
alldb_2 = alldb_2[(alldb_2['site'].astype(str).str.isdigit()) & (alldb_2['site'].str.len() == 5)]      # เลือกมาเฉพาะ คอลัมน์ site ที่เป็นตัวเลข & มีตัวเลข เท่ากับ 5 ตัว
print(alldb_2.shape)                                                                            
alldb_2

(37965, 9)

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13:08:39,มีตะกอน,0,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14:22:22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16:31:45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14:46:08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15:27:45,ปกติ (เหลืองใส),4,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11:36:34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18:10:29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12:14:41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13:58:01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13:57:58,ปกติ (เหลืองใส),1,99999

### แก้เงื่อนไขเปลี่ยน time เป็น hh-mm-ss

In [12]:
alldb_2['time'] = alldb_2['time'].replace(':','-',regex=True) # กำหนดรูปแบบของ time เป็น hh-mm-ss
alldb_2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13-08-39,มีตะกอน,0,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14-22-22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11-36-34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18-10-29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),1,99999

### แก้เงื่อนไขเปลี่ยน urine มีค่า String

In [13]:
alldb_2['urine'] = alldb_2['urine'].astype('str')
print(alldb_2.shape)
alldb_2

(37965, 9)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
185,85879,shmpdrmtgc.png,2022-03-24,OPPO CPH2293,05194,13-08-39,มีตะกอน,0,0000
188,27529,ADC54E82-4225-4DE6-89A6-A7E556C15FB1,2022-02-25,"iPhone13,1",04999,14-22-22,ปกติ (เหลืองใส),0,0000
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11-36-34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18-10-29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),1,99999

###ov เป็นตัวเลข มีค่าตั้งแต่ 0-4 (0 คือไม่พบโรค 1-4 คือพบโรคที่ระดับความรุนแรงต่างๆ)
โดยจะกำหนดให้แทนด้วยตัวเลขดังต่อไปนี้ 
* ติดเชื้อ +2 = 4
* มีเม็ดเลือดแดง = 4
* สีฟ้า หรือน้ำเงิน = 3
* สีน้ำนม = 2
* ขุ่น = 1
* มีตะกอน = 1
* ปกติ (เหลืองใส) = 0
* ใสเป็นน้ำเปล่า = 0

In [17]:
set(alldb_2['ov'])  #ดูข้อมูลคอลัมน์ ov

{'0', '1', '2', '3', '4', 'ติดเชื้อ +2 '}

In [19]:
alldb_2['ov'].replace({'ขุ่น':'1','ติดเชื้อ +2 ':'4','ปกติ (เหลืองใส)':'0','มีตะกอน':'1','มีเม็ดเลือดแดง':'4',
'สีน้ำนม':'2','สีฟ้า หรือน้ำเงิน':'3','ใสเป็นน้ำเปล่า':'0',}, inplace=True)  #แทนค่าข้อมูลตามที่เรากำหนด

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [21]:
set(alldb_2['ov'])  #เชคข้อมูลคอลัมน์ ov ข้อมูลเป็นตามที่กำหนดแล้ว

{'0', '1', '2', '3', '4'}

###PartitionKey เป็นตัวเลข 5 หลัก (ตัวเลขเท่านั้น)
* เลือกมาเฉพาะข้อมูลที่เป็นตัวเลข 5 หลัก

In [23]:
set(alldb_2['PartitionKey'])  #ดูค่าข้อมูลคอลัมน์ PartitionKey

{'00520',
 '02365',
 '06021',
 '01537',
 '03048',
 '02638',
 '01797',
 '00698',
 '02340',
 '04628',
 '01251',
 '01849',
 '00764',
 '00118',
 '00246',
 '01037',
 '00210',
 '03995',
 '05341',
 '00389',
 '00606',
 '01308',
 '91123',
 '99771',
 '00676',
 '01688',
 '02262',
 '09031',
 '01410',
 '107',
 '00554',
 '00925',
 '00441',
 '00798',
 '01441',
 '01843',
 '01229',
 '03461',
 '00358',
 '00619',
 '01956',
 '00206',
 '01738',
 '00642',
 '01497',
 '01505',
 '02672',
 '00970',
 '03217',
 '00234',
 '03402',
 '00030',
 '00868',
 '04736',
 '08903',
 '08982',
 '02989',
 '87606',
 '01291',
 '00409',
 '001',
 '00784',
 '01104',
 '03266',
 '02812',
 '02765',
 '00932',
 '01230',
 '01933',
 '00298',
 '02178',
 '02437',
 '04684',
 '01147',
 '05209',
 '03403',
 '01513',
 '02440',
 '00695',
 '01577',
 '08910',
 '02770',
 '05247',
 '05985',
 '01012',
 '03069',
 '02481',
 '08949',
 '06022',
 '08926',
 '00105',
 '02763',
 '05382',
 '06037',
 '01816',
 '00181',
 '00413',
 '05975',
 '02020',
 '02714',
 '00429',
 '00479',
 '01690',
 '08990',
 '00436',
 '02494',
 '00117',
 '10969',
 '00176',
 '00353',
 '00649',
 '01095',
 '02454',
 '00765',
 '00933',
 '01848',
 '02648',
 '03180',
 '000102',
 '00372',
 '00819',
 '02301',
 '03071',
 '02329',
 '00015',
 '02860',
 '02206',
 '02257',
 '01773',
 '02006',
 '00731',
 '06729',
 '02710',
 '00180',
 '03278',
 '08995',
 '01466',
 '01288',
 '06058',
 '01841',
 '00095',
 '02421',
 '02062',
 '03238',
 '02457',
 '01259',
 '01467',
 '06060',
 '02068',
 '01262',
 '04782',
 '10974',
 '03504',
 '00212',
 '00823',
 '01663',
 '01814',
 '08969',
 '03725',
 '02874',
 '03042',
 '00229',
 '00884',
 '08963',
 '01311',
 '01867',
 '04014',
 '04061',
 '00049',
 '00842',
 '00697',
 '03125',
 '01570',
 '02741',
 '02900',
 '01611',
 '05232',
 '06045',
 '01939',
 '01605',
 '02475',
 '01820',
 '02500',
 '00673',
 '00371',
 '03224',
 '00445',
 '03563',
 '06026',
 '01890',
 '00050',
 '00585',
 '02912',
 '00200',
 '03227',
 '08519',
 '00846',
 '00849',
 '08979',
 '06005',
 '03122',
 '09008',
 '01157',
 '02049',
 '01575',
 '00021',
 '02438',
 '03126',
 '01949',
 '02621',
 '03550',
 '01668',
 '00122',
 '01178',
 '02076',
 '01064',
 '00506',
 '00998',
 '01033',
 '01725',
 '200',
 '04672',
 '00324',
 '00241',
 '00194',
 '05292',
 '00096',
 '00936',
 '00603',
 '02866',
 '33333',
 '01383',
 '02550',
 '33664',
 '00801',
 '01159',
 '01703',
 '01051',
 '01885',
 '00896',
 '02892',
 '01834',
 '02505',
 '02704',
 '00804',
 '03137',
 '09016',
 '03365',
 '08985',
 '05117',
 '01493',
 '00887',
 '04649',
 '02258',
 '04087',
 '01810',
 '02078',
 '02242',
 '04643',
 '05095',
 '00316',
 '02158',
 '01416',
 '01329',
 '05128',
 '02377',
 '06717',
 '01985',
 '02468',
 '02602',
 '00510',
 '00278',
 '01796',
 '00192',
 '03327',
 '06063',
 '02139',
 '02754',
 '03015',
 '00699',
 '02768',
 '01911',
 '00230',
 '02013',
 '02038',
 '01998',
 '08967',
 '03541',
 '01422',
 '00760',
 '00850',
 '01982',
 '01746',
 '00379',
 '01085',
 '02643',
 '05262',
 '08917',
 '08935',
 '00258',
 '02531',
 '00895',
 '05113',
 '02678',
 '04016',
 '00683',
 '02761',
 '00487',
 '01258',
 '00239',
 '01446',
 '03273',
 '00967',
 '00455',
 '00701',
 '02578',
 '01541',
 '02807',
 '01856',
 '00366',
 '02504',
 '00728',
 '02755',
 '05318',
 '01970',
 '05841',
 '179',
 '00341',
 '00572',
 '01829',
 '08947',
 '00471',
 '02267',
 '01349',
 '01561',
 '02670',
 '01789',
 '05099',
 '00342',
 '00714',
 '00571',
 '02403',
 '02526',
 '01142',
 '02908',
 '02167',
 '00790',
 '00204',
 '00693',
 '09027',
 '00039',
 '00196',
 '01454',
 '00051',
 '01594',
 '02713',
 '0030',
 '00878',
 '01803',
 '01543',
 '01972',
 '00483',
 '02991',
 '05139',
 '00191',
 '00134',
 '01571',
 '01979',
 '01895',
 '00521',
 '01389',
 '00202',
 '00733',
 '00889',
 '05313',
 '02543',
 '02499',
 '03049',
 '01751',
 '05109',
 '88432',
 '03298',
 '01470',
 '01009',
 '00129',
 '06001',
 '01903',
 '02497',
 '00125',
 '00712',
 '02523',
 '02534',
 '08932',
 '04685',
 '08964',
 '01140',
 '01426',
 '00953',
 '00387',
 '00575',
 '01767',
 '01395',
 '09044',
 '05111',
 '06730',
 '02616',
 '03533',
 '01966',
 '00330',
 '02676',
 '05362',
 '00909',
 '02880',
 '08984',
 '00875',
 '02823',
 '00670',
 '00808',
 '00988',
 '03155',
 '00590',
 '09039',
 '00421',
 '00972',
 '00089',
 '02507',
 '00474',
 '00901',
 '03305',
 '00995',
 '01791',
 '01685',
 '02882',
 '00802',
 '01352',
 '03124',
 '00787',
 '00911',
 '00509',
 '125',
 '00511',
 '01699',
 '01254',
 '05248',
 '01082',
 '01857',
 '00837',
 '000167',
 '00128',
 '01579',
 '02731',
 '00844',
 '02982',
 '03804',
 '06013',
 '04802',
 '08940',
 '02273',
 '02857',
 '02054',
 '02208',
 '02295',
 '00162',
 '02757',
 '00329',
 '00978',
 '01898',
 '03136',
 '00677',
 '01564',
 '01397',
 '01233',
 '01253',
 '01392',
 '00010',
 '05126',
 '02811',
 '01479',
 '00706',
 '00114',
 '00154',
 '01049',
 '01219',
 '00092',
 '01409',
 '02051',
 '02190',
 '05974',
 '00137',
 '01872',
 '00037',
 '01907',
 '01661',
 '00377',
 '00404',
 '03826',
 '01118',
 '02420',
 '00270',
 '00942',
 '04054',
 '01431',
 '00757',
 '04688',
 '05960',
 '00792',
 '01303',
 '00776',
 '01603',
 '00145',
 '04186',
 '01824',
 '08918',
 '00864',
 '01852',
 '09029',
 '00641',
 '01390',
 '04738',
 '01046',
 '00184',
 '02631',
 '00794',
 '00715',
 '02027',
 '03462',
 '02293',
 '05115',
 '08503',
 '10998',
 '08902',
 '02112',
 '03415',
 '00003',
 '01236',
 '124',
 '01017',
 '01384',
 '00527',
 '03544',
 '02345',
 '00164',
 '03339',
 '04168',
 '09038',
 '00907',
 '03151',
 '02789',
 '03509',
 '02040',
 '00044',
 '02313',
 '01743',
 '08920',
 '03032',
 '00646',
 '00306',
 '05235',
 '06003',
 '00449',
 '02100',
 '02864',
 '06726',
 '00357',
 '01214',
 '01224',
 '00869',
 '00888',
 '01013',
 '02059',
 '00583',
 '01517',
 '00789',
 '00710',
 '08743',
 '01511',
 '00272',
 '00811',
 '00332',
 '00596',
 '01381',
 '02776',
 '02917',
 '04165',
 '72483',
 '00711',
 '02767',
 '02567',
 '01343',
 '05093',
 '00425',
 '00048',
 '00486',
 '08966',
 '01388',
 '99999',
 '03949',
 '01075',
 '08521',
 '01572',
 '02565',
 '02652',
 '02559',
 '01044',
 '02843',
 '03335',
 '00480',
 '03153',
 '00478',
 '01469',
 '04071',
 '04666',
 '01927',
 '00863',
 '00700',
 '01014',
 '01250',
 '00654',
 '03708',
 '02237',
 '06030',
 '01456',
 '05092',
 '03347',
 '03265',
 '02060',
 '00266',
 '00038',
 '00951',
 '02814',
 '10979',
 '01807',
 '03425',
 '01902',
 '00779',
 '01828',
 '05133',
 '00281',
 '01846',
 '02781',
 '02854',
 '72093',
 '01267',
 '00026',
 '00755',
 '00843',
 '01035',
 '01342',
 '06024',
 '02337',
 '00877',
 '01149',
 '03101',
 '00276',
 '02224',
 '06025',
 '01379',
 '02132',
 '02905',
 '00472',
 '01774',
 '03419',
 '01963',
 '03936',
 '01300',
 '04675',
 '00187',
 '02708',
 '01736',
 '02162',
 '10506',
 '03361',
 '03565',
 '04697',
 '01940',
 '00172',
 '02110',
 '01024',
 '02230',
 '04052',
 '00317',
 '10990',
 '02361',
 '00659',
 '01337',
 '01909',
 '00495',
 '01625',
 '01059',
 '08929',
 '00456',
 '00962',
 '01500',
 '03113',
 '02211',
 '05114',
 '05263',
 '04667',
 '00307',
 '01793',
 '05996',
 '00773',
 '03379',
 '01787',
 '01120',
 '02397',
 '01675',
 '00732',
 '00635',
 '08936',
 '00941',
 '01226',
 '05141',
 '01519',
 '00438',
 '01947',
 '01332',
 '08956',
 '04793',
 '01402',
 '00490',
 '00383',
 '00543',
 '01152',
 '00141',
 '01502',
 '00012',
 '02204',
 '02426',
 '02773',
 '02858',
 '03978',
 '05101',
 '02719',
 '02223',
 '01264',
 '04619',
 '01484',
 '10984',
 '05323',
 '00556',
 '01298',
 '06029',
 '00446',
 '00053',
 '00870',
 '00398',
 '02124',
 '00338',
 '01198',
 '04018',
 '02061',
 '02487',
 '04621',
 '04732',
 '01274',
 '11006',
 '00369',
 '04183',
 '00638',
 '05227',
 '05770',
 '00917',
 '02847',
 '01186',
 '00570',
 '04019',
 '00360',
 '02451',
 '01532',
 '09035',
 '00607',
 '03140',
 '02796',
 '02071',
 '01614',
 '01717',
 '00002',
 '00688',
 '00305',
 '01131',
 '01231',
 '00463',
 '06053',
 '00244',
 '03394',
 '04100',
 '00956',
 '00112',
 '01865',
 '00041',
 '01612',
 '01644',
 '05992',
 '05999',
 '01356',
 '01197',
 '03393',
 '01483',
 '00553',
 '03261',
 '08996',
 '00578',
 '01896',
 '03108',
 '04638',
 '00020',
 '01499',
 '02238',
 '09018',
 '05719',
 '00561',
 '02434',
 '00203',
 '01239',
 '02402',
 '06034',
 '01785',
 '01897',
 '52',
 '01946',
 '05125',
 '00993',
 '00435',
 '03244',
 '01145',
 '05104',
 '00734',
 '01276',
 '03961',
 '00100',
 '01360',
 '00396',
 '03521',
 '03552',
 '00116',
 '00130',
 '05121',
 '02011',
 '00186',
 '02938',
 '01399',
 '01770',
 '01471',
 '08994',
 '01837',
 '01967',
 '01756',
 '00267',
 '01724',
 '02589',
 '01596',
 '02215',
 '02877',
 '02045',
 '04640',
 '00668',
 '01460',
 '08965',
 '01859',
 '05100',
 '00485',
 '00138',
 '01351',
 '02075',
 '02595',
 '01113',
 '02750',
 '01365',
 '04624',
 '03154',
 '04674',
 '00261',
 '01443',
 '01978',
 '02305',
 '02620',
 '03334',
 '00071',
 '01526',
 '01088',
 '00279',
 '00265',
 '03325',
 '04785',
 '01222',
 '01617',
 '03183',
 '00839',
 '00904',
 '02041',
 '06041',
 '04636',
 '05396',
 '03179',
 '00923',
 '00376',
 '03438',
 '03284',
 '02903',
 '02170',
 '01879',
 '03178',
 '01983',
 '02690',
 '00541',
 '02980',
 '05727',
 '02766',
 '23',
 '04642',
 '06002',
 '00929',
 '00931',
 '01321',
 '00859',
 '01953',
 '03064',
 '00526',
 '05244',
 '01076',
 '00593',
 '05207',
 '03290',
 '00749',
 '02622',
 '02682',
 '00255',
 '01817',
 '02423',
 '00535',
 '01461',
 '02720',
 '02218',
 '06016',
 '00394',
 '00110',
 '01589',
 '01704',
 '02687',
 '09040',
 '03437',
 '02379',
 '01330',
 '00169',
 '05238',
 '08941',
 '04637',
 '02336',
 '01417',
 '01549',
 '03395',
 '05986',
 '02244',
 '00822',
 '02073',
 '09000',
 '02469',
 '01220',
 '00274',
 '03510',
 '01363',
 '00031',
 '01711',
 '03326',
 '08968',
 '02355',
 '03176',
 '01414',
 '00295',
 '01801',
 '02887',
 '01588',
 '03225',
 '01296',
 '01752',
 '00655',
 '03546',
 '06721',
 '03035',
 '05172',
 '01763',
 '03245',
 '01645',
 '00185',
 '01723',
 '04136',
 '08961',
 '09012',
 '00470',
 '01634',
 '01232',
 '02003',
 '10986',
 '01691',
 '02467',
 '03052',
 '03939',
 '02944',
 '00812',
 ...}

In [25]:
alldb_3 = alldb_2[(alldb_2['PartitionKey'].astype(str).str.isdigit()) & (alldb_2['PartitionKey'].str.len() == 5)]  #เลือกข้อมูลที่เป็นตัวเลข 5 หลักเท่านั้น
alldb_3

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001
193,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001
194,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11-36-34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18-10-29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),1,99999

##ตารางไฟล์ alldb

In [26]:
alldb_3

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey
190,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),0,00000
191,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001
192,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001
193,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001
194,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001
...,...,...,...,...,...,...,...,...,...
39812,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11-36-34,ขุ่น,1,99999
39813,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18-10-29,มีตะกอน,0,99999
39814,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",1,99999
39815,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),1,99999
39816,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),1,99999

In [27]:
alldb_2.isnull().any()  #เชค Missing พบว่าไม่มี Missing

user            False
RowKey          False
date            False
phone           False
site            False
time            False
urine           False
ov              False
PartitionKey    False
dtype: bool

#Datahospital_list

In [28]:
hospital_list = pd.read_excel(os.path.join(path,'hospital_list.xlsx'))   #ข้อมูล Datahospital_list
hospital_list

,hcode,name,zone_code,zone_name,provincecode,province,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,00001,สำนักงานสาธารณสุขจังหวัดสมุทรปราการ,6,สาขาพื้นที่(ระยอง),11.0,สมุทรปราการ,1.0,เมืองสมุทรปราการ,1.0,ปากน้ำ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,สป,SPK
1,00002,สำนักงานสาธารณสุขจังหวัดนนทบุรี,4,สาขาพื้นที่(สระบุรี),12.0,นนทบุรี,1.0,เมืองนนทบุรี,4.0,บางกระสอ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,นบ,NBI
2,00003,สำนักงานสาธารณสุขจังหวัดปทุมธานี,4,สาขาพื้นที่(สระบุรี),13.0,ปทุมธานี,1.0,เมืองปทุมธานี,1.0,บางปรอก,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,ปท,PTE
3,00004,สำนักงานสาธารณสุขจังหวัดพระนครศรีอยุธยา,4,สาขาพื้นที่(สระบุรี),14.0,พระนครศรีอยุธยา,1.0,พระนครศรีอยุธยา,3.0,หอรัตนไชย,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อย,AYA
4,00005,สำนักงานสาธารณสุขจังหวัดอ่างทอง,4,สาขาพื้นที่(สระบุรี),15.0,อ่างทอง,1.0,เมืองอ่างทอง,8.0,บ้านอิฐ,1.0,สำนักงานสาธารณสุขจังหวัด,NaN,NaN,อท,ATG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17098,99990,ศูนย์สุขภาพชุมชนโรงพยาบาลอุตรดิตถ์(สาขา 2 วัดท...,2,สาขาพื้นที่(พิษณุโลก),53.0,อุตรดิตถ์,1.0,เมืองอุตรดิตถ์,1.0,ท่าอิฐ,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,อต,UTT
17099,99991,ศูนย์สุขภาพชุมชนโรงพยาบาลกุยบุรี,5,สาขาพื้นที่(ราชบุรี),77.0,ประจวบคีรีขันธ์,2.0,กุยบุรี,1.0,กุยบุรี,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ปข,PKN
17100,99993,ศูนย์สุขภาพชุมชนตำบลวัดเพลง,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,9.0,วัดเพลง,3.0,วัดเพลง,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR
17101,99996,คลินิกทันตกรรม สสจ.ศรีสะเกษ,10,สาขาพื้นที่(อุบลราชธานี),33.0,ศรีสะเกษ,1.0,เมืองศรีสะเกษ,11.0,โพนข่า,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,ศก,SSK
17102,99998,ศูนย์สุขภาพชุมชนตำบลบางแพ,5,สาขาพื้นที่(ราชบุรี),70.0,ราชบุรี,6.0,บางแพ,2.0,วังเย็น,8.0,ศูนย์สุขภาพชุมชน ของ รพ.,10.0,1 ปฐมภูมิ,รบ,RBR

#รวมตาราง alldb และ hospital_list

In [30]:
data_merge = alldb_3.merge(hospital_list,how='left',left_on='site',right_on='hcode')  #รวมตารางโดยให้ alldb_3 เป็น ตารางหลัก เชื่อมด้วยคีย์หลัก site และ คีย์รองคือ hcode
data_merge

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
0,06223,kfpwuaqldj.png,2022-03-23,Xiaomi 21081111RG,13777,16-31-45,ปกติ (เหลืองใส),0,00000,13777,...,1.0,เมืองขอนแก่น,1.0,ในเมือง,12.0,โรงพยาบาล นอก สธ.,NaN,NaN,ขก,KKN
1,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,06307,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
2,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,05328,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
3,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001,06302,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
4,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001,05059,...,10.0,นาดูน,6.0,หัวดง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37891,99999,F45E78D3-7D89-47A3-8207-C705377E0E0A,2022-03-11,"iPhone14,2",99999,11-36-34,ขุ่น,1,99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37892,99999,lnlohgqckf.png,2022-03-10,Samsung SM-G998B,99999,18-10-29,มีตะกอน,0,99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37893,99999,vkdocpmjiv.png,2022-03-10,Samsung SM-G998B,99999,12-14-41,"ขุ่น, มีเม็ดเลือดแดง",1,99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37894,99999,vrvyfnvayq.png,2022-03-10,Samsung SM-G998B,99999,13-58-01,ปกติ (เหลืองใส),1,99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37895,99999,zuhbtvyrce.png,2022-03-10,Samsung SM-G998B,99999,13-57-58,ปกติ (เหลืองใส),1,99999,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

##กำจัดค่า Missing

In [31]:
data_merge.isnull().any()  #เชค Missing พบว่ายังมีค่า Missing

user             False
RowKey           False
date             False
phone            False
site             False
time             False
urine            False
ov               False
PartitionKey     False
hcode             True
name              True
zone_code         True
zone_name         True
provincecode      True
province          True
amphurcode        True
amphur            True
tamboncode        True
tambon            True
code4             True
name5             True
code9             True
name10            True
short_thai        True
short_english     True
dtype: bool

In [32]:
data_merge1 = data_merge.dropna()  #จัดการ Missing ด้วยการ drop na
data_merge1

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
1,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,06307,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
2,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,05328,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
3,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001,06302,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
4,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001,05059,...,10.0,นาดูน,6.0,หัวดง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
5,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),0,00001,06334,...,9.0,ทองแสนขัน,4.0,น้ำพี้,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37879,68768,B7F36631-D2C4-4EB5-852D-790BFAFDFD71,2022-03-24,"iPhone11,8",11088,10-30-22,ปกติ (เหลืองใส),2,89170,11088,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
37880,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,"iPhone11,8",11088,10-29-37,ปกติ (เหลืองใส),0,90470,11088,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
37881,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,"iPhone11,8",11088,10-24-40,ปกติ (เหลืองใส),1,91123,11088,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
37882,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,"iPhone11,8",11088,10-25-32,ปกติ (เหลืองใส),1,99444,11088,...,14.0,ห้วยผึ้ง,3.0,นิคมห้วยผึ้ง,7.0,โรงพยาบาลชุมชน,21.0,2.1 ทุติยภูมิระดับต้น,กส,KSN
37883,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,"iPhone10,5",05396,11-03-40,ปกติ (เหลืองใส),0,99771,05396,...,10.0,คำม่วง,9.0,เนินยาง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN

In [33]:
removes = data_merge.shape[0] - data_merge1.shape[0]    #เชคว่าจากการดรอปข้อมูลหายกี่เปอร์เซนต์ ซึ่งพบว่าหาย1.885215938169095% ของข้อมูลทั้งหมด ยอมรับได้
print(f'size before drop = {data_merge.shape[0]}')
print(f'size aftre drop = {data_merge1.shape[0]}')
print(f'we loss {100*(removes/data_merge.shape[0])}% of data')

size before drop = 37896
size aftre drop = 37195
we loss 1.8497994511294067% of data

In [34]:
print(data_merge.shape)   #จำนวนแถวก่อนDropna
print(data_merge1.shape)   #จำนวนแถวหลังDropna

(37896, 25)
(37195, 25)

In [35]:
data_merge1.head()  #เชคหัวคอลัมน์

,user,RowKey,date,phone,site,time,urine,ov,PartitionKey,hcode,...,amphurcode,amphur,tamboncode,tambon,code4,name5,code9,name10,short_thai,short_english
1,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),4,00001,06307,...,7.0,พิชัย,2.0,บ้านดารา,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
2,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),4,00001,05328,...,18.0,ฆ้องชัย,3.0,โคกสะอาด,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,กส,KSN
3,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),3,00001,06302,...,5.0,ฟากท่า,4.0,สองห้อง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT
4,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),3,00001,05059,...,10.0,นาดูน,6.0,หัวดง,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,มค,MKM
5,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),0,00001,06334,...,9.0,ทองแสนขัน,4.0,น้ำพี้,18.0,โรงพยาบาลส่งเสริมสุขภาพตำบล,10.0,1 ปฐมภูมิ,อต,UTT

##เลือกมาเฉพาะคอมลัมน์ที่ต้องการใช้

In [36]:
datause = data_merge1[['user','RowKey','date','ov','phone','site','time','urine','PartitionKey','name','zone_name','province','amphur','tambon','short_thai','short_english']]
datause

,user,RowKey,date,ov,phone,site,time,urine,PartitionKey,name,zone_name,province,amphur,tambon,short_thai,short_english
1,12015,00859DB9-1BD9-4825-B246-3DC25EFD1924,2022-03-30,4,"iPhone12,3",06307,14-46-08,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านเกาะ ตำบลบ้านดารา,สาขาพื้นที่(พิษณุโลก),อุตรดิตถ์,พิชัย,บ้านดารา,อต,UTT
2,91811,1376ACA2-AFA5-4457-967A-D2FCF908E6A5,2022-03-30,4,"iPhone14,3",05328,15-27-45,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านโคกประสิทธิ์,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ฆ้องชัย,โคกสะอาด,กส,KSN
3,95821,1914EE67-CD8F-47EE-A968-2772911AA5DF,2022-03-30,3,"iPhone13,4",06302,10-16-46,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลสองห้อง,สาขาพื้นที่(พิษณุโลก),อุตรดิตถ์,ฟากท่า,สองห้อง,อต,UTT
4,13361,1A219EE7-3647-4D7D-A8C0-AE638E69D889,2022-03-29,3,"iPhone9,4",05059,12-26-38,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านดอนดู่,สาขาพื้นที่(ขอนแก่น),มหาสารคาม,นาดูน,หัวดง,มค,MKM
5,28241,1AFBC992-AF2F-4F97-AE6D-443F30ED8402,2022-03-31,0,"iPhone13,3",06334,14-57-41,ปกติ (เหลืองใส),00001,โรงพยาบาลส่งเสริมสุขภาพตำบลน้ำพี้,สาขาพื้นที่(พิษณุโลก),อุตรดิตถ์,ทองแสนขัน,น้ำพี้,อต,UTT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37879,68768,B7F36631-D2C4-4EB5-852D-790BFAFDFD71,2022-03-24,2,"iPhone11,8",11088,10-30-22,ปกติ (เหลืองใส),89170,โรงพยาบาลห้วยผึ้ง,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ห้วยผึ้ง,นิคมห้วยผึ้ง,กส,KSN
37880,68768,899A7591-50C9-40BC-9746-A831A08DE980,2022-03-24,0,"iPhone11,8",11088,10-29-37,ปกติ (เหลืองใส),90470,โรงพยาบาลห้วยผึ้ง,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ห้วยผึ้ง,นิคมห้วยผึ้ง,กส,KSN
37881,68768,BF39F27C-1B43-4C97-A034-D7A579BED2B6,2022-03-24,1,"iPhone11,8",11088,10-24-40,ปกติ (เหลืองใส),91123,โรงพยาบาลห้วยผึ้ง,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ห้วยผึ้ง,นิคมห้วยผึ้ง,กส,KSN
37882,68768,D8A3A9EA-929E-4CEB-BFDF-C9BE093EA663,2022-03-24,1,"iPhone11,8",11088,10-25-32,ปกติ (เหลืองใส),99444,โรงพยาบาลห้วยผึ้ง,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,ห้วยผึ้ง,นิคมห้วยผึ้ง,กส,KSN
37883,99771,E04D3D60-B916-40A1-AE77-91CCD89DD084,2022-03-31,0,"iPhone10,5",05396,11-03-40,ปกติ (เหลืองใส),99771,โรงพยาบาลส่งเสริมสุขภาพตำบลบ้านสูงเนิน,สาขาพื้นที่(ขอนแก่น),กาฬสินธุ์,คำม่วง,เนินยาง,กส,KSN

#นำข้อมูลไปใช้งาน

In [37]:
datause.to_csv('datause.csv') 
datause.to_csv(os.path.join(path,'datause.csv'))

In [39]:
datause.to_csv('Datause.csv', encoding='utf-8')